language: generic

sudo:required

services:
  - docker

before_install:
  - docker build -t jamieecode/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true jamieecode/react-test-app npm run test


after_success:
  - docker build -t jamieecode/docker-frontend ./frontend
  - docker build -t jamieecode/docker-backend ./backend
  - docker build -t jamieecode/docker-nginx ./nginx

  - echo "DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --pasword-stdin

  - docker push jamieecode/docker-frontend
  - docker push jamieecode/docker-backend
  - docker push jamieecode/docker-nginx
