language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jamieecode/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true jamieecode/react-test-app npm run test

after_success:
  - docker build -t jamieecode/docker-frontend:latest ./frontend
  - docker build -t jamieecode/docker-backend:latest ./backend
  - docker build -t jamieecode/docker-nginx:latest ./nginx

  - echo "DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push jamieecode/docker-frontend:latest
  - docker push jamieecode/docker-backend:latest
  - docker push jamieecode/docker-nginx:latest

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fulltstack-app"
  env: "Docker-fulltstack-app-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-533267259028
  bucket_path: "docker-fulltstack-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
